name: BigBrother
version: 1.9.1-SNAPSHOT
main: me.taylorkelly.bigbrother.BigBrother
authors: ['tkelly','n3x15']
latest-release-url: 'http://ci.nexisonline.net:8080/job/BigBrother/Recommended/artifact/target/BigBrother.jar'
commands:
  bb:
    description: All of the BigBrother commands
    usage: Command unrecognised by BigBrother. See documentation or use /bb help.